# Nice Flor-S Remote Control Configuration

# Pigpio connection details
pigpio_host: "127.0.0.1"

# GPIO pin number on Raspberry Pi
gpio: 27

# Remote control serial number (hexadecimal)
serial: 0xabcdef0

# Starting code value (will be updated automatically in code.txt)
start_code: 0

# Put here how many time in seconds it takes for the thing to go from open to close, if 0 or less it's disabled and
# you cannot use the partial open automatically with home assistant
time_from_open_to_close: 0


# MQTT Configuration
mqtt:
  broker: "yourbroker"
  port: 1883
  # Optional: Add username and password if your broker requires authentication
  username: "user"
  password: "name"

  # Base topic for Home Assistant discovery and communication
  topic_base: "homeassistant/cover/nice_blind"